# Generated by Django 5.2.7 on 2025-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Municipal Staff', 'Municipal Staff'), ('External Professional', 'External Professional'), ('Applicant', 'Applicant')], max_length=30),
        ),
    ]
