# Generated by Django 5.2.7 on 2025-11-06 16:27

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, default=applications.models.generate_application_number, max_length=20, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('project_description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_status', models.CharField(db_index=True, default='DRAFT', max_length=30)),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='applications/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('document_category', models.CharField(choices=[('Site Plan', 'Site Plan'), ('Building Plans', 'Building Plans'), ('Structural Drawings', 'Structural Drawings'), ('Engineering Reports', 'Engineering Reports'), ('Proof of Ownership', 'Proof of Ownership'), ('Other', 'Other')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Application Status Histories',
                'db_table': 'application_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(default='Toronto', max_length=50)),
                ('province', models.CharField(default='ON', max_length=2)),
                ('postal_code', models.CharField(db_index=True, max_length=7)),
                ('legal_description', models.TextField(blank=True)),
                ('ward', models.CharField(blank=True, max_length=50)),
                ('zoning_designation', models.CharField(blank=True, max_length=50)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
            },
        ),
    ]
