# Generated by Django 5.2.7 on 2025-11-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type_name', models.CharField(max_length=100)),
                ('permit_category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('standard_processing_days', models.IntegerField(default=90)),
                ('requires_multiple_departments', models.BooleanField(default=False)),
                ('required_documents', models.TextField(blank=True)),
                ('application_form_template', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permit_types',
                'ordering': ['permit_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status_name', models.CharField(max_length=100)),
                ('status_description', models.TextField(blank=True)),
                ('status_category', models.CharField(choices=[('Initial', 'Initial'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('is_open_status', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('color_code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'statuses',
                'ordering': ['display_order'],
            },
        ),
    ]
