# Generated by Django 5.2.7 on 2025-11-06 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_department', models.CharField(blank=True, max_length=100)),
                ('processing_deadline', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permittype')),
            ],
            options={
                'db_table': 'permits',
                'ordering': ['-submission_date'],
            },
        ),
    ]
