# Generated by Django 5.2.7 on 2025-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittype',
            name='permit_category',
            field=models.CharField(choices=[('Building', 'Building'), ('Demolition', 'Demolition'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Mechanical', 'Mechanical'), ('Zoning', 'Zoning'), ('Environmental', 'Environmental'), ('Signage', 'Signage'), ('Fire Safety', 'Fire Safety'), ('Other', 'Other')], max_length=50),
        ),
    ]
