# Generated by Django 5.2.7 on 2025-11-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_permittype_permit_category'),
        ('users', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='assigned_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AlterField(
            model_name='permittype',
            name='permit_category',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Right of Way', 'Right of Way')], max_length=50),
        ),
    ]
