# Generated by Django 5.2.7 on 2025-11-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('Building Code', 'Building Code'), ('Zoning', 'Zoning'), ('Fire Safety', 'Fire Safety'), ('Engineering', 'Engineering'), ('Heritage', 'Heritage')], max_length=50)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('review_decision', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Approved with Conditions', 'Approved with Conditions'), ('Requires Additional Information', 'Requires Additional Information'), ('Rejected', 'Rejected')], max_length=50)),
                ('findings_summary', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('review_duration', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='applications.application')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
