# Generated by Django 4.2.26 on 2025-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=10, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('physical_location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('permit_id', models.AutoField(primary_key=True, serialize=False)),
                ('permit_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Construction', 'Construction'), ('Building', 'Building'), ('Demolition', 'Demolition'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Mechanical', 'Mechanical'), ('Zoning', 'Zoning'), ('Environmental', 'Environmental'), ('Signage', 'Signage'), ('Fire Safety', 'Fire Safety'), ('Right of Way', 'Right of Way'), ('Health & Safety', 'Health & Safety'), ('Environmental', 'Environmental'), ('Business', 'Business'), ('Special Events', 'Special Events'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('standard_processing_days', models.IntegerField(default=90)),
                ('requires_multiple_departments', models.BooleanField(default=False)),
                ('required_documents', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_departments', models.ManyToManyField(blank=True, related_name='permits', to='permits.department')),
            ],
            options={
                'db_table': 'permit',
                'ordering': ['permit_name'],
            },
        ),
    ]
