# Generated by Django 4.2.26 on 2025-11-13 17:29

import applications.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_number', models.CharField(db_index=True, default=applications.models.generate_application_number, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('project_description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_status', models.CharField(db_index=True, default='DRAFT', max_length=30)),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='applications/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('document_category', models.CharField(choices=[('Site Plan', 'Site Plan'), ('Building Plans', 'Building Plans'), ('Structural Drawings', 'Structural Drawings'), ('Engineering Reports', 'Engineering Reports'), ('Proof of Ownership', 'Proof of Ownership'), ('Other', 'Other')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status_name', models.CharField(max_length=100)),
                ('status_description', models.TextField(blank=True)),
                ('status_category', models.CharField(choices=[('Initial', 'Initial'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('is_open_status', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('color_code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'statuses',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'Application Status Histories',
                'db_table': 'application_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
