# Generated by Django 4.2.26 on 2025-11-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_initial'),
        ('permits', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='associated_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='real_estate.realestate'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='permits.permit'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application'], name='application_applica_f4d12e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='application_applica_ec5a77_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['current_status'], name='application_current_e21b90_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_by'], name='application_created_1075e4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-submission_date'], name='application_submiss_37857a_idx'),
        ),
    ]
