# Generated by Django 4.2.26 on 2025-11-13 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 18, 53, 15, 358600, tzinfo=datetime.timezone.utc)),
        ),
    ]
