# Generated by Django 4.2.26 on 2025-11-13 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 20, 13, 53, 473055, tzinfo=datetime.timezone.utc)),
        ),
    ]
