# Generated by Django 4.2.26 on 2025-11-13 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 20, 23, 45, 451122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
