# Generated by Django 4.2.26 on 2025-11-13 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 20, 26, 28, 691353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
