# Generated by Django 4.2.26 on 2025-11-13 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 20, 28, 39, 143996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
