# Generated by Django 4.2.26 on 2025-11-13 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 20, 34, 2, 726415, tzinfo=datetime.timezone.utc)),
        ),
    ]
