# Generated by Django 4.2.26 on 2025-11-13 20:43

import applications.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_alter_application_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 20, 43, 25, 184026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, validators=[applications.models.validate_file_size]),
        ),
    ]
