# Generated by Django 4.2.26 on 2025-11-13 21:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_application_created_date_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='application_current_e03df0_idx',
            old_name='application_current_e21b90_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 21, 46, 17, 788905, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.status'),
        ),
    ]
