# Generated by Django 4.2.26 on 2025-11-13 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_rename_application_current_e21b90_idx_application_current_e03df0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 21, 49, 30, 194486, tzinfo=datetime.timezone.utc)),
        ),
    ]
