# Generated by Django 4.2.26 on 2025-11-13 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_alter_application_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 22, 5, 25, 445100, tzinfo=datetime.timezone.utc)),
        ),
    ]
