# Generated by Django 4.2.26 on 2025-11-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('Building Code', 'Building Code'), ('Zoning', 'Zoning'), ('Fire Safety', 'Fire Safety'), ('Engineering', 'Engineering'), ('Heritage', 'Heritage')], max_length=50)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('review_decision', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Approved with Conditions', 'Approved with Conditions'), ('Requires Additional Information', 'Requires Additional Information'), ('Rejected', 'Rejected')], max_length=50)),
                ('findings_summary', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('review_duration', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='applications.application')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='permits.department')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['application'], name='reviews_applica_734098_idx'), models.Index(fields=['reviewer'], name='reviews_reviewe_965d53_idx'), models.Index(fields=['is_completed'], name='reviews_is_comp_54f17b_idx')],
            },
        ),
    ]
