# Generated by Django 4.2.26 on 2025-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('real_estate_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('street_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(default='Toronto', max_length=50)),
                ('province', models.CharField(default='ON', max_length=2)),
                ('postal_code', models.CharField(db_index=True, max_length=7)),
                ('legal_description', models.TextField(blank=True)),
                ('ward', models.CharField(blank=True, max_length=50)),
                ('zoning_designation', models.CharField(blank=True, max_length=50)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Real Estates',
                'db_table': 'real_estate',
                'indexes': [models.Index(fields=['postal_code'], name='real_estate_postal__690684_idx'), models.Index(fields=['city', 'street_name'], name='real_estate_city_c8ec33_idx')],
            },
        ),
    ]
