# Generated by Django 4.2.26 on 2025-11-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permission_level', models.IntegerField(default=1)),
                ('can_submit_applications', models.BooleanField(default=False)),
                ('can_review_applications', models.BooleanField(default=False)),
                ('can_approve_applications', models.BooleanField(default=False)),
                ('can_configure_system', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_all_applications', models.BooleanField(default=False)),
                ('can_generate_reports', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('Admin', 'Admin'), ('Municipal Staff', 'Municipal Staff'), ('External Professional', 'External Professional'), ('Applicant', 'Applicant')], max_length=30)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Locked', 'Locked'), ('Pending Activation', 'Pending Activation')], default='Active', max_length=20)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('require_password_change', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth', to='permits.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auth', to='authentication.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'authetication',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['email'], name='autheticati_email_00393f_idx'), models.Index(fields=['username'], name='autheticati_usernam_a47d75_idx'), models.Index(fields=['account_status'], name='autheticati_account_6a6c5b_idx')],
            },
        ),
    ]
